### ISSUE TITLE
System Apps section is empty if HideMeX is used to hide apps section

### ISSUE THREAD

**Issue by DesignatedJM02** [akemin-dayo/PreferenceOrganizer2#40]
When I installed the tweak I saw that I had "System Apps", "Social", "Tweaks" and "App Store Apps". Which is normal. When I looked into "App Store Apps" I noticed nothing showing. The other 3 sections seemed to work.

I tried reinstalling the Tweak as well as Rocket bootstrap. App Store Apps section still didn't want to show anything.

**Comment by JMccormick264** [comment]
It seems to be a tweak conflict. Disabled all but PreferenceOrganizer2.dylib and PreferenceLoader.dylib and the App Store section populated.

**Comment by JMccormick264** [comment]
Alright. I found it. It's In HideMeX
HideMeX > First Party Apps Section > Settings > "Disable Apps Section".
With that toggled ON the App Store Apps section of Preference Organizer2 not to show up. With That toggled OFF in HideMeX, the App Store Section works perfectly in PrefOrganizer 2

**Comment by angelXwind** [comment]
Can you confirm this still happens on 4.0.4 (or whatever the latest version is when you read this)?

In any case, as this isn't really a bug with PreferenceOrganiser 2, I'm not sure if I'd really be able to fix it as I think the issue lies more with how HideMeX is hiding the specifiers to begin with :/

**Comment by akemin-dayo** [comment]
Closed this issue due to inactivity (and not having gotten a reply).

Feel free to re-open if you want.
