### ISSUE TITLE
Tweak in arab (Bad language)

### ISSUE THREAD

**Issue by Elsodo** [akemin-dayo/PreferenceOrganizer2#47]
Hello, 

Everything is in the title, i'll atached two pics to showing you what's the issues.
(My basic language is French)

![IMG_1101](https://user-images.githubusercontent.com/53092639/61549547-9840cd00-aa50-11e9-9712-65901282af90.jpg)
![IMG_1102](https://user-images.githubusercontent.com/53092639/61549548-98d96380-aa50-11e9-9cac-96e7a9cb9c14.jpg)

**Comment by akemin-dayo** [comment]
It's… been a while, so I'm not really sure if you're still having this problem, but this is generally caused by having the language in question in your preferred language list, even if it is underneath French (your primary language).

To fix this, either remove Arabic from your preferred languages list, or put English above Arabic and below French.

Feel free to re-open the issue if you still are experiencing this behaviour.
