### ISSUE TITLE
postrm script fails on iOS 14 because wrong shell is used

### ISSUE THREAD

**Issue by jacobseptember** [akemin-dayo/PreferenceOrganizer2#51]
I realize iOS 14 is not supported yet, but...

When trying to uninstall, dpkg returns an error that is traced back to line 3 of postrm: `declare: not found`. The script's hashbang is `#!/bin/sh` which in older iOS versions referenced `bash`; in iOS 14 some other shell is referenced by default, and that shell does not support `declare`.

Editing the script's hashbang to `#!/bin/bash` allows the uninstall to proceed.

**Comment by m1stadev** [comment]
This is due to the Procursus switching `/bin/sh` from `bash` to `dash`, which means that the package maintainer scripts should be POSIX-compliant (which they should be if they're using `/bin/sh` anyways). The easy fix would be to make the package maintainer scripts use `/bin/bash`, but ideally the scripts should be rewritten to be POSIX-compliant.

**Comment by akemin-dayo** [comment]
Fixed as of commit `ba14f6560ac3eb19125e1dfb0ec065ec89132950`.

This bug really has just been sitting there for _years_ now, huh? I usually get the hashbang invocation correct, not sure what happened here l o l

(The script is not POSIX-compliant because I generally use `bash`-specific features in all my scripts.)

**Comment by m1stadev** [comment]
Could you add `bash` as a dependency as well? (request from Hayden)

**Comment by akemin-dayo** [comment]
Added as of commit `48fc0bf057c0552f28635c9c90afbbcc482ddff6`.

Does the Procursus bootstrap no longer ship `bash` by default, then? (As in — will I have to start adding `bash` to my `Depends` fields in the future?)

**Comment by m1stadev** [comment]
Procursus still ships `bash` by default, but I believe that Hayden intends to remove `bash` from the default packages eventually, so I'd recommend doing so. Also, thank you for fixing this!

**Comment by Diatrus** [comment]
Thanks for fixing this, and yes, sometime in the far far future, I was hoping to remove bash. I’ll obviously announce that intention first and give people time to add to their depends, but I hope it’ll work out.

**Comment by akemin-dayo** [comment]
Huh — curious, what are the reasons behind this decision? Seems to me that all it'd do is break compatibility with people's packages with not much upsides (aside from, I guess, one less thing to maintain)?

**Comment by Diatrus** [comment]
@akemin-dayo Right now Procursus ships 3 default shells. I just wanted to knock that down to 2. Less *essential* packages is always a goal I aim toward. It wouldn’t be removed for previous iOS versions, it just wouldn’t be shipped in the first iOS 16 jailbreak (assuming that’s when I chose to get rid of it by default).
